include:
  - docker-compose.monitoring.yaml

services:

  nginx:
    image: 'jc21/nginx-proxy-manager:2.10.4'
    ports:
      - '80:80'
      - '443:443'
      - '8090:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
     # - ./nginx/nginx.conf:/data/nginx/custom/http_top.conf
    restart: always
    depends_on:
      - frontend
      - backend
      - prometheus
      - grafana
      - adminer
      - cadvisor
      - loki
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - mynetwork
  
volumes:
  db_data:
  #data:
  letsencrypt:


networks:
  mynetwork:
    driver: bridge